{
  "name"                 :  "Business Lending Application",
  "summary"              :  """Business Lending Application.""",
  "category"             :  "Account",
  "version"              :  "1.0.0",
  "sequence"             :  1,
  "author"               :  "Target Integration.",
  "website"              :  "http://www.targetintegration.com",
  "description"          :  """Business Lending Application""",
  "depends"              :  [
                             'base',
                             'mail',
                            ],
  "data"                 :  [
                              'security/ir.model.access.csv',
                              'data/ir_sequence_data.xml',
                              'data/mail_template.xml',
                              'data/ir_cron.xml',
                              'reports/report_action.xml',
                              'views/report_acknowledging_letter.xml',
                              'views/report_business_account.xml',
                              'views/business_borrower.xml',
                              'views/business_relationship.xml',
                              'views/business_application.xml',
                              'views/business_interest_rate.xml',
                              'views/business_assets.xml',
                              'wizard/business_close.xml',
                              'wizard/message_wizard.xml',
                              'views/business_checklist.xml',
                              'views/business_account.xml',
                              'views/decision_group.xml',
                              'views/menu.xml',
                            ],
  "application"          :  True,
  "installable"          :  True,
  "auto_install"         :  False,
}